### ISSUE TITLE
Explosion graphic

### ISSUE THREAD

**Issue by skiesel** [velour/grawl#2]
We need some sort of sweet explosion graphic -- possibly a bomb too, so we can blow up walls/trees when the game is impossible to win because someone didn't write a reasonable level generator.

**Comment by eaburns** [comment]
Awesome!

**Comment by chrissexton** [comment]
Probably needs to have a mushroom cloud and me may even need to do some foley for an audio effect.

**Comment by eaburns** [comment]
+1

**Comment by mccoyst** [comment]
I'm on it.

**Comment by mccoyst** [comment]
Fixed by d84d00e67705d8.
